[package]
name = "building-blocks"
version = "0.2.1"
edition = "2018"
authors = ["Duncan <bonsairobo@gmail.com>"]
description = "Data types, collections, and algorithms for working with maps on 2D and 3D integer lattices. Commonly known as voxel data."
license = "MIT"
repository = "https://github.com/bonsairobo/building-blocks"
keywords = ["voxel"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["mesh", "procgen", "search"]

image = ["building_blocks_image"]
mesh = ["building_blocks_mesh"]
glam = ["building_blocks_core/glam"]
lz4 = ["building_blocks_storage/lz4"]
mint = ["building_blocks_core/mint"]
nalgebra = ["building_blocks_core/nalgebra"]
ncollide = ["building_blocks_search/ncollide"]
procgen = ["building_blocks_procgen"]
search = ["building_blocks_search"]
snappy = ["building_blocks_storage/snappy"]
vox = ["building_blocks_vox"]

[workspace]
members = ["crates/*"]
exclude = ["benches"]

[profile.dev]
opt-level = 2

[profile.release]
lto = true

[profile.bench]
lto = true

[dependencies]
building_blocks_core = { path = "crates/building_blocks_core", version = "0.2.1" }
building_blocks_storage = { path = "crates/building_blocks_storage", version = "0.2.1" }

# Optional, feature-gated
building_blocks_image = { path = "crates/building_blocks_image", version = "0.2", optional = true }
building_blocks_mesh = { path = "crates/building_blocks_mesh", version = "0.2", optional = true }
building_blocks_procgen = { path = "crates/building_blocks_procgen", version = "0.2", optional = true }
building_blocks_search = { path = "crates/building_blocks_search", version = "0.2", optional = true }
building_blocks_vox = { path = "crates/building_blocks_vox", version = "0.2", optional = true }

[dev-dependencies]
bevy = "0.3" # for examples
log = "0.4"
noise = "0.6"

[[bin]]
name = "measure_compression_rate"
required-features = ["lz4", "snappy"]

[[example]]
name = "bevy_meshing"
path = "examples/bevy_meshing/bevy_meshing.rs"
